### ISSUE TITLE
Timestamp shows when the line ends

### ISSUE THREAD

**Issue by miniol** [WoodenNautilus/tabby-serial-timestamp#2]
Version: 1.0.197
Platform: Windows x64 10.0.19045
Plugins: workspace-manager, serial-timestamp (v1.0.2), save-output, quick-cmds
Frontend: xterm-webgl

My terminal line output ends with CR/LF. When there is a couple of seconds break in serial port outputs, I have noticed that the new timestamp shows immediately after the last line ending. After a short brake in lines receiving (a couple of seconds), the first new line that comes has no timestamp (it seems to be "assigned" to the previous timestamp).

![image](https://user-images.githubusercontent.com/2788676/236418573-6b563abd-1f8e-4d59-809a-ea596e482779.png)

**Comment by WoodenNautilus** [comment]
Hello @miniol,

I have released yesterday a version 1.0.3 which contains a complete refactor of the timestamp mechanism.
Could you try this new one and tell me if the issue still occurs ?

**Comment by miniol** [comment]
How to install 1.0.3 - I uninstalled the 1.0.2 but still I can only install 1.0.2 and no options for update?

**Comment by WoodenNautilus** [comment]
Sorry, I made a mistake. Version 1.0.2 is the latest.
In the initial description of the issue, you wrote "My terminal line output ends with .". Does it means the output ends with a space ? Or a dot ?
Is it the line which only contains the timestamp that ends with this char ?

**Comment by miniol** [comment]
I meant CR/LF but it looks like the chat cannot display curly braces... 
Already corrected.

**Comment by WoodenNautilus** [comment]
Could you try to capture the same output, without the plugin enabled, and send this to me in a txt file ?
There must be a case that I missed in my algorithm.

**Comment by miniol** [comment]
Here you have raw output captured by other app (YAT terminal). As you can see,, there is a couple of seconds break after the second line and then I get a timestamp in Tabby. I'm not quite sure if this is a problem of your plugin since Tabby inserts new empty line after this particular line (other terminals do not):

```
(12:12:26.059) <ESC>[0;32mI (1438764) LTE_MID: Buffer data: 0801120612040880fe03<ESC>[0m<CR><LF>
(12:12:26.059) <ESC>[0;32mI (1438766) LTE_MID: Middleware has acknowledged with OK<ESC>[0m<CR><LF>
(12:12:33.782) <ESC>[0;32mI (1446477) DATA_ACQ: Current frame timestamp is: 05-05-23 10:12:31 UTC<ESC>[0m<CR><LF>
(12:12:33.782) <ESC>[0;32mI (1446477) SENSOR: PM1 3.47, PM2.5 4.13, PM10 4.13, CNT 10<ESC>[0m<CR><LF>
(12:12:33.782) <ESC>[0;32mI (1446480) SENSOR: T 25.1, H 23, P 997, R 400294.69, CNT 10<ESC>[0m<CR><LF>

```

**Comment by WoodenNautilus** [comment]
Nothing too exotic here.
Two options here. My code is buggy or there is something weird happening because of the escape sequences.
I will have to look into my code and find a way to have escape sequences sent to a COM port.
I will let you know if I find something.

One last question. Is it happening randomly or always on the same trace ? Apparently related to a delay between the arrival of the previous trace and the faulty one ?

**Comment by miniol** [comment]
Yes, this happens always when there is a longer break in serial transmission - don't know exactly how long, but it happens also in other places in my log - so I would say, the issue is related to the delay between output lines.

**Comment by miniol** [comment]
It looks for me that the timestamp is displayed on each new line, doesn't matter if any data follows. 
I'm not sure if this is feasible, but it would the best to add the timestamp on the beginning of the newly received data characters before displaying the line, as the timestamp should reflect the time of data receiving, rather than new line sign.

**Comment by WoodenNautilus** [comment]
Actually it does not work like guessed.
When the LF char is received, a flag is set to tell that the end of a line is reached. Then, when new data is received, this fag is checked. If it is set, then the date is prepended and the flag is unset. If it is not set, then the data is displayed as it is received.

**Comment by miniol** [comment]
Ok, thanks for the clarification.
Another my observation is, that the plugin works great if there is no ANSI coloring on serial output. I have a different device that outputs only ASCII characters, and the timestamps work OK there.

**Comment by WoodenNautilus** [comment]
Interesting observation. For me this is a confirmation that sending ANSI coloured text to the terminal will allow me to reproduce. Once I can reproduce this, I am pretty confident I will be able to solve this issue pretty quickly.

**Comment by WoodenNautilus** [comment]
Hello @miniol.
I spent the afternoon of yesterday trying to reproduce your issue. I was able to send the data you provided, with the break of few seconds between the 2 blocks of data and could not get the issue to appear.
![image](https://user-images.githubusercontent.com/86767647/236621572-976bc91a-635b-4949-bb80-15f72fc99f50.png)

To move further I will need your help.
It would require you run a specific version of the plugin. This special version displays logs in the DevTools.
To see those logs you will have to run Tabby in **debug mode** by executing **Tabby.exe -d**.

If you agree to help me, let me know and I will send you the modified plugin with some instructions telling you where to place these files.

**Comment by miniol** [comment]
Ok, I'd be happy to help. Just send me instructions.

**Comment by WoodenNautilus** [comment]
[tabby-serial-timestamp_debugging.zip](https://github.com/WoodenNautilus/tabby-serial-timestamp/files/11423176/tabby-serial-timestamp_debugging.zip)

Attached to this message there if a Zip file containing what you need. The PDF should contain all the explanations, whereas if you think I forgot something, write me a message !

Thanks for your help !

**Comment by WoodenNautilus** [comment]
Hello,
I updated the documentation with a much simpler way to retrieve the logs.

[Debug_ Serial-Timestamp_Plugin.pdf](https://github.com/WoodenNautilus/tabby-serial-timestamp/files/11429253/Debug_.Serial-Timestamp_Plugin.pdf)

**Comment by miniol** [comment]
Ok, I’ve captured the attached log. I hope this helps.

Regards,
Michal

**Comment by WoodenNautilus** [comment]
Hello @miniol,

Unfortunately, the logs don't show any trace of the debug version of serial-timestamp. Are you sur you have replaced the files of the dist folder ? Then reproduced the issue ?

**Comment by miniol** [comment]
Ok, I removed the previous log and did the debug once again. Try this one.

**Comment by WoodenNautilus** [comment]
It is promising ! Would you happen to know at which trace the issue appeared ? I forgot to ask you to do a screenshot of the terminal as well. I apologize.

**Comment by miniol** [comment]
The new log once again in attachement.
It is strange for me since the line marked “1” shows a number of times in the file (lines 221,239, 255 and more). The line marked as “2” logs in lines 443 and 451.

***@***.***

**Comment by WoodenNautilus** [comment]
I think I understood what is going on.
Below is an example I will base my explanations on.
When the line "Protobuf frame of size" arrives, it is prepended with the date and contains a LF.
Then, what arrives is a CR + LF, also prepended with the date. This explains the line with only the date on the initial screenshot.
After that, a series of escape sequences and "> " which are preceded with the date, as expected. This sequence does not contains any LF.
The issue is that after this arrives a CR, without a LF. This erases the date and all the other chars of the line.

I never considered something like this would happen. I will fix it so that the next line is timestamped correctly. I hope this will solve your problem. Thanks for your help.

info: Loop number 6
info: Remaining data contains LF
info: line [0;32mI (2943405) DATA_ACQ: Protobuf frame of size 118 has been queued [0m

info: line data 0x1b 0x5b 0x30 0x3b 0x33 0x32 0x6d 0x49 0x20 0x28 0x32 0x39 0x34 0x33 0x34 0x30 0x35 0x29 0x20 0x44 0x41 0x54 0x41 0x5f 0x41 0x43 0x51 0x3a 0x20 0x50 0x72 0x6f 0x74 0x6f 0x62 0x75 0x66 0x20 0x66 0x72 0x61 0x6d 0x65 0x20 0x6f 0x66 0x20 0x73 0x69 0x7a 0x65 0x20 0x31 0x31 0x38 0x20 0x68 0x61 0x73 0x20 0x62 0x65 0x65 0x6e 0x20 0x71 0x75 0x65 0x75 0x65 0x64 0x1b 0x5b 0x30 0x6d 0xd 0xa
info: line is the beginning of the line thus prepend the date
info: Unsetting startOfLine
info: line contains LF thus setting startOfLine
info: -------------------------- Leaving feedFromSession --------------------------
info: -------------------------- Entering feedFromSession --------------------------
info: Provided string

info: Provided data 0xd 0xa
info: occurences 1
info: data.toString('utf8').split(CRLF OR LF).length 2
info: data.toString('utf8').length 2
info: Loop number 0
info: Remaining data contains LF
info: line

info: line data 0xd 0xa
info: line is the beginning of the line thus prepend the date
info: Unsetting startOfLine
info: line contains LF thus setting startOfLine
info: -------------------------- Leaving feedFromSession --------------------------
info: -------------------------- Entering feedFromSession --------------------------
info: Provided string [1G
info: Provided data 0x1b 0x5b 0x31 0x47
info: occurences 1
info: data.toString('utf8').split(CRLF OR LF).length 1
info: data.toString('utf8').length 4
info: Loop number 0
info: Remaining data does not contain LF
info: line [1G
info: line data 0x1b 0x5b 0x31 0x47
info: line is the beginning of the line thus prepend the date
info: Unsetting startOfLine
info: -------------------------- Leaving feedFromSession --------------------------
info: -------------------------- Entering feedFromSession --------------------------
info: Provided string [0J
info: Provided data 0x1b 0x5b 0x30 0x4a
info: occurences 1
info: data.toString('utf8').split(CRLF OR LF).length 1
info: data.toString('utf8').length 4
info: Loop number 0
info: Remaining data does not contain LF
info: line [0J
info: line data 0x1b 0x5b 0x30 0x4a
info: line is not the beginning of the line. Do not prepend the date
info: -------------------------- Leaving feedFromSession --------------------------
info: -------------------------- Entering feedFromSession --------------------------
info: Provided string >
info: Provided data 0x3e 0x20
info: occurences 1
info: data.toString('utf8').split(CRLF OR LF).length 1
info: data.toString('utf8').length 2
info: Loop number 0
info: Remaining data does not contain LF
info: line >
info: line data 0x3e 0x20
info: line is not the beginning of the line. Do not prepend the date
info: -------------------------- Leaving feedFromSession --------------------------
info: -------------------------- Entering feedFromSession --------------------------
info: Provided string [3G
info: Provided data 0x1b 0x5b 0x33 0x47
info: occurences 1
info: data.toString('utf8').split(CRLF OR LF).length 1
info: data.toString('utf8').length 4
info: Loop number 0
info: Remaining data does not contain LF
info: line [3G
info: line data 0x1b 0x5b 0x33 0x47
info: line is not the beginning of the line. Do not prepend the date
info: -------------------------- Leaving feedFromSession --------------------------
info: -------------------------- Entering feedFromSession --------------------------
info: Provided string [2K
info: Provided data 0x1b 0x5b 0x32 0x4b
info: occurences 1
info: data.toString('utf8').split(CRLF OR LF).length 1
info: data.toString('utf8').length 4
info: Loop number 0
info: Remaining data does not contain LF
info: line [2K
info: line data 0x1b 0x5b 0x32 0x4b
info: line is not the beginning of the line. Do not prepend the date
info: -------------------------- Leaving feedFromSession --------------------------
info: -------------------------- Entering feedFromSession --------------------------
info: Provided string
info: Provided data 0xd
info: occurences 1
info: data.toString('utf8').split(CRLF OR LF).length 1
info: data.toString('utf8').length 1
info: Loop number 0
info: Remaining data does not contain LF
info: line
info: line data 0xd
info: line is not the beginning of the line. Do not prepend the date
info: -------------------------- Leaving feedFromSession --------------------------

**Comment by WoodenNautilus** [comment]
I just released the v1.0.3 which contains the patch for your issue. Tell me if it works !

**Comment by miniol** [comment]
Thanks for the quick fix. Now it works very good. In fact I’m receiving empty lines from my device, but now all the lines (no matter empty or not) are correctly timestamped.
Good job!
;-)

**Comment by WoodenNautilus** [comment]
Thanks for helping me find an fix this design flaw !
